from typing import Dict, Any

class ReportExporter:
    @staticmethod
    def to_markdown(story_data: Dict[str, Any]) -> str:
        """Export executive data story as GitHub-Flavored Markdown."""
        dataset_name = story_data.get("dataset_name", "Dataset")
        domain = story_data.get("domain", "General Analytics")
        story = story_data.get("story", {})

        md_lines = [
            f"# Executive Intelligence Report: {dataset_name}",
            f"**Domain**: {domain}  |  **Generated by**: InsightAI Autonomous Analytics Engine\n",
            "---",
            "## 1. Executive Summary",
            story.get("executive_summary", ""),
            "\n## 2. Overall Performance",
            story.get("overall_performance", ""),
            "\n## 3. Growth Drivers",
            story.get("growth_drivers", ""),
            "\n## 4. Underperforming Areas & Bottlenecks",
            story.get("underperforming_areas", ""),
            "\n## 5. Statistical Anomalies & Outliers",
            story.get("anomalies", ""),
            "\n## 6. Strategic Risks",
            story.get("risks", ""),
            "\n## 7. High-Value Opportunities",
            story.get("opportunities", ""),
            "\n## 8. Prioritized Strategic Actions"
        ]

        for i, act in enumerate(story.get("recommended_actions", []), 1):
            md_lines.append(f"{i}. **{act}**")

        return "\n\n".join(md_lines)
